# -*- coding: utf-8 -*-
"""Current_application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17l3tjybvTLd0O6VZEPG9VhUoplz8OObz
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# pip install pyvis
# pip install pandas
# pip install streamlit
# pip install requests
#

!pip install faiss-cpu

!pip install biopython
import Bio

import streamlit as st
import pandas as pd
import os
import numpy as np

# Download the Cloudflare Tunnel binary
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

import subprocess
import time

# 1. Kill any old processes to free up the port
!pkill streamlit
!pkill cloudflared

# 2. Start Streamlit in the background with the specific stability flags
# These flags are CRITICAL for preventing JS loading errors
cmd = "streamlit run app.py --server.port 8501 --server.enableCORS false --server.enableXsrfProtection false &"
subprocess.Popen(cmd, shell=True)

# 3. Wait a few seconds for the server to spin up
time.sleep(5)

# 4. Launch the Cloudflare Tunnel
# This will output a link ending in .trycloudflare.com
print("--- YOUR APP LINK IS BELOW ---")
!cloudflared tunnel --url http://localhost:8501

